name: telgpt_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - requests
  - pydantic
  - faiss-cpu
  - pip:
      - python-telegram-bot==21.6
      - openai>=1.30.0
      - python-dotenv>=1.0.1
      - tiktoken
      - PyMuPDF>=1.24.0
      - python-dotenv
      - pandas>=2.2.0
      - openpyxl>=3.1.2
      - scikit-learn>=1.4.0
      - python-dotenv
